version: '3.8'

services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: silverstripe
      MARIADB_DATABASE: silverstripe
      MARIADB_USER: silverstripe
      MARIADB_PASSWORD: silverstripe

  web:
    image: silverstripecloud/base:8.0-apache
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "8000:80"
    environment:
      SS_DATABASE_CLASS: MySQLDatabase
      SS_DATABASE_SERVER: db
      SS_DATABASE_USERNAME: silverstripe
      SS_DATABASE_PASSWORD: silverstripe
      SS_DATABASE_NAME: silverstripe
      SS_ENVIRONMENT_TYPE: dev
      SS_DEFAULT_ADMIN_USERNAME: admin
      SS_DEFAULT_ADMIN_PASSWORD: admin

  composer:
    image: composer
    command: composer install --ignore-platform-reqs --no-interaction
    volumes:
      - .:/app

volumes:
  db_data: {}
